name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li9NTI038Ii8ItEV"
GITHUB_OWNER = "A13788899580"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere.ooon.eu.org/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere.ooon.eu.org"

